### PR TITLE
Keyboard settings

### PR DESCRIPTION
**Pull request by kimo-k**
https://github.com/day8/re-frame-10x/issues/314

- [X] Toggle keyboard event handling in the settings
- [x]  Bind the `show-panel!` key in the settings

### CODE REVIEW

**Review by coltnz — COMMENTED** [review]
lgtm generally.

I wonder if we shouldn't be changing the default here given it doesn't work well for Firefox. We'll run straight into [xkcd](https://xkcd.com/1172/) if we do, so perhaps we use a different default on Firefox?

**Comment by kimo-k** [comment]
Different defaults per browser could work, but could also lead to more confusion. I imagine the new option to set your own binding, and the new docs for programmatically opening the panel, should be relief enough for anyone who is currently hacking their `Ctrl-h` somehow.

How do we feel about `Ctrl-Shift-X`? It seems unused by mainstream browsers. 

Firefox does use it to switch text direction (such as for Arabic input), but only when a text input element is focused. Conveniently, 10x [ignores the key event](https://github.com/day8/re-frame-10x/blob/4cb9fc10e8f9035eb82b11afafdaa21bc0e3547b/src/day8/re_frame_10x.cljs#L47) in this situation.

It is used by VSCode and Teams to open panels, but that's probably okay.

**Comment by sirmspencer** [comment]
Anything for the readme?

**Comment by kimo-k** [comment]
Hey @sirmspencer, I did notice an inconsistency in the readme for this. I fixed that & added a mention of the settings. Let me know if any other particulars come up.

**Comment by sirmspencer** [comment]
Looks good, thanks.

**Comment by mike-thompson-day8** [comment]
There is mention of ctrl-h in re-frame-template README ... Good idea to
bump it's deps in that template too.

**Comment by ourkwest** [comment]
Is there any way to configure the keyboard shortcut after this change?

It seems to be set dynamically now with the code:

```
(rf/inject-cofx ::local-storage/load {:key "key-bindings" :or {:show-panel {:key "X"
                                                                               :altKey false
                                                                               :ctrlKey true
                                                                               :metaKey false
                                                                               :shiftKey true}}})
```

Is there a way to override the default? Reason being that 1Password (a popular browser extension) defaults to Ctrl+Shift+X.
I'm guessing I could build my own re-frame-10x, but if I just need to send an event somewhere in my application code that would be preferable. Unfortunately I'm not yet familiar enough with re-frame-10x to see how to do this myself. Any help gratefully appreciated!

**Pull request merged**
