### PR TITLE
Add button to expand or collapse entire app-db

### LINKED ISSUE #82: One click to collapse/expand entire data structure tree
A button in the app-state tab that expands/collapses entire data structure tree.

### PR DESCRIPTION
**Pull request by MawiraIke**
This PR fixes #82 
Adds a button beside sort and delete app-db that can be used to expand or collapse the entire app db.

mouse over expand

### CODE REVIEW

**Comment by superstructor** [comment]
Sorry me merging some of your other PRs out of order has caused conflicts with `master`. Please resolve the conflicts on this PR @MawiraIke

**Review by superstructor — CHANGES_REQUESTED** [review]
merge conflicts to resolve with `master`, otherwise code looks good

**Comment by MawiraIke** [comment]
@superstructor sorry about the merge conflicts. I am fixing them ASAP.

**Comment by superstructor** [comment]
Sorry, merge conflicts from other PRs to resolve @MawiraIke

**Comment by MawiraIke** [comment]
👍🏼 @superstructor this is good to go now.

**Pull request merged**
