### PR TITLE
Add settings option to enable or disable rendering of path annotations

### LINKED ISSUE #341: [Enhancement]: Add toggle option to turn on/off path annotations for app-db
### What do you suggest?

The path annotation feature in re-frame-10x 1.2.0 is a nice addition which allows users to copy paths of objects in the app-db and also copy nested children within the app-db etc. However, this processing takes longer when the app-db is larger. For small maps without deep nesting the difference in performance is not really visible but in cases when the app-db is larger than 3mb, I have got speeds of about 7 seconds. This is quite a lot and might render `10x` unusable for some users/use cases.
To this end, a PR is needed to add a toggle option to turn on/off rendering path annotations. When this option is off, we will call [(body ...)](https://github.com/day8/re-frame-10x/blob/master/src/day8/re_frame_10x/components/cljs_devtools.cljs#L231) without the `render-paths?` option

### PR DESCRIPTION
**Pull request by MawiraIke**
Fixes #341 
Adds a new settings option to toggle rendering of path annotations

preview

### CODE REVIEW

**Comment by mike-thompson-day8** [comment]
Now I'm seeing this option in settings, I'm having second thoughts.  This option should probably be a tick box in the app-db tab itself, closer to where it has its effect (at the expense of some vertical real estate in that tab). 

So, I would suggest:
  - there's a tickbox at the top of the `app-db` panel with the label "data path annotations". 
  - to the right of this tickbox there is an info button (?) that causes a popup containing the following explanatory text ... 

    > When ticked, you can right-click on the rendered data (below) to obtain path data and cause focus etc.  But this feature comes with a performance hit on rendering which is proportional to the size/depth of app-db.  So, if your app-db is large and you are noticing a delay/pause in rendering app-db, untick this option to get better performance.

**Comment by MawiraIke** [comment]
Sounds great @mike-thompson-day8 ,
I will proceed to make that addition to this PR.

**Comment by MawiraIke** [comment]
This PR has been updated. The tickbox is now located in the app-db tab. 
i.e

preview

**Comment by mike-thompson-day8** [comment]
@MawiraIke Okay, looking good. One thing: can we get the information popup to be about 60 to 80 characters wide.  That provides for the best reading experience.  Very wide text is hard to read. 

I'll leave any further code review to @superstructor

**Comment by MawiraIke** [comment]
This PR has been updated with the recommended changes.

**Comment by superstructor** [comment]
Good to see that the `local-storage/save` interceptor is being used so that this setting will survive page refreshes.

Overall looks good, thanks @MawiraIke 👍🏻

**Pull request merged**
